### ISSUE TITLE
Scraping Issue

### ISSUE THREAD

**Issue by curphey** [dcaslin/runscraper#1]
Hey Dave, looks like they have changed the UI so the following CSS class is no longer available?

yarn run v1.9.4
$ yarn run build && yarn run serve ****************
$ yarn run build-ts && yarn run tslint
$ tsc
$ tslint -c tslint.json -p tsconfig.json
$ node dist/main.js ********************
 ██████████████████░░░░░░░░░░░░░░░░░░░░░░ 45% | ETA: 6s | 90/200Error: TimeoutError: waiting for selector ".connect-container" failed: timeout 30000ms exceed
Done

**Comment by dcaslin** [comment]
Hmmm... Looks like I'll need to make some updates. I hadn't gotten to running this in a while. I had no idea anyone else might be using it!

**Comment by dcaslin** [comment]
All fixed with an upgraded package.json/yarn.lock. Thanks for the heads up!
